const motivationMessages = [
    "N'abandonne jamais. Les plus grandes réalisations de la vie se produisent juste après avoir été sur le point d'abandonner.",
    "La détermination est clé pour réussir. Gardez le cap et ne laissez rien vous arrêter.",
    "La vie est un défi, relevez-le avec courage et détermination.",
    "Ne vous comparez jamais à personne. Vous êtes unique et vous avez votre propre chemin à suivre.",
    "Croire en soi est le premier pas vers la réussite.",
    "L'effort aujourd'hui détermine le succès de demain.",
    "La musculation n'est pas une option, c'est un mode de vie.",
    "Le corps s'adapte aux défis que nous lui donnons, donnez-lui ce qu'il mérite.",
    "La sueur aujourd'hui signifie des résultats demain.",
    "La persévérance est la clé du succès en musculation.",
    "L'entraînement est le meilleur remède pour la dépression, l'anxiété et le stress.",
    "L'effort physique est la clé pour déverrouiller votre potentiel.",
    "La musculation est la meilleure façon de développer votre confiance en vous.",
    "La persévérance et la détermination sont les ingrédients clés pour atteindre vos objectifs en musculation.",
    "La musculation n'est pas seulement pour votre corps, c'est aussi pour votre esprit et votre âme.",
    "L'entraînement est la clé pour déverrouiller votre force intérieure.",
    "L'effort physique est la clé pour développer votre caractère.",
    "La musculation vous aide à construire un corps fort et un esprit plus fort.",
    "La sueur aujourd'hui signifie la satisfaction demain.",
    "La musculation n'est pas seulement pour le corps, c'est aussi pour l'esprit.",
    "La persévérance et la détermination sont les ingrédients clés pour atteindre vos objectifs en sport.",
    "Le succès en musculation vient de la persévérance à surmonter les obstacles.",
    "La musculation est la meilleure façon de développer votre détermination et votre persévérance.",
    "L'entraînement quotidien est la clé pour atteindre vos objectifs à long terme.",
    "La musculation est le moyen de devenir la meilleure version de soi-même.",
    "La musculation n'a pas de limites, juste des défis à relever.",
    "L'entraînement est la clé pour développer votre force physique et mentale.",
    "La musculation vous permet de découvrir votre véritable potentiel.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en musculation.",
    "Le succès en musculation vient de la détermination à ne jamais abandonner.",
    "La musculation vous aide à devenir plus fort à chaque entraînement.",
    "L'entraînement est la meilleure façon de développer votre confiance en vous.",
    "La musculation vous permet de vous surpasser chaque jour.",
    "L'effort physique est la clé pour développer votre caractère et votre détermination.",
    "La musculation n'est pas seulement pour le corps, c'est aussi pour l'esprit et l'âme.",
    "La persévérance est la clé pour atteindre vos objectifs en musculation.",
    "L'entraînement quotidien est la clé pour construire un corps fort et un esprit plus fort.",
    "La sueur aujourd'hui signifie la force demain.",
    "La musculation vous permet de devenir plus fort à chaque entraînement.",
    "L'effort physique est la clé pour développer votre détermination et votre persévérance.",
    "La musculation vous aide à découvrir votre véritable potentiel.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en sport.",
    "Le succès en musculation vient de la persévérance à surmonter les obstacles.",
    "La musculation est la meilleure façon de développer votre confiance en vous.",
    "L'entraînement est la clé pour déverrouiller votre force intérieure.",
    "La musculation n'a pas de limites, juste des défis à relever.",
    "L'entraînement est la clé pour développer votre force physique et mentale.",
    "La musculation vous permet de découvrir votre véritable potentiel.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en musculation.",
    "Le succès en musculation vient de la détermination à ne jamais abandonner.",
    "La musculation vous aide à devenir plus fort à chaque entraînement.",
    "L'entraînement est la meilleure façon de développer votre confiance en vous.",
    "La musculation vous permet de vous surpasser chaque jour.",
    "L'effort physique est la clé pour développer votre caractère et votre détermination.",
    "La musculation n'est pas seulement pour le corps, c'est aussi pour l'esprit et l'âme.",
    "L'entraînement est la clé pour construire une mentalité de gagnant.",
    "La musculation vous aide à devenir plus fort mentalement et physiquement.",
    "La persévérance est la clé pour développer votre force intérieure.",
    "La musculation vous permet de dépasser vos limites.",
    "L'entraînement quotidien est la clé pour atteindre vos objectifs à long terme.",
    "La musculation vous aide à devenir plus fort à chaque entraînement.",
    "L'effort physique est la clé pour développer votre détermination et votre persévérance.",
    "La musculation vous aide à construire une vie plus saine et plus forte.",
    "L'entraînement est la clé pour développer votre discipline.",
    "La musculation vous aide à devenir plus confiant en vous.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en sport.",
    "Le succès en musculation vient de la persévérance à surmonter les obstacles.",
    "La musculation est la meilleure façon de développer votre caractère et votre détermination.",
    "L'entraînement est la clé pour déverrouiller votre potentiel caché.",
    "La musculation vous aide à devenir plus fort chaque jour.",
    "L'effort physique est la clé pour construire une vie plus saine et plus forte.",
    "La musculation vous aide à développer votre force intérieure.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en musculation.",
    "Le succès en musculation vient de la détermination à ne jamais abandonner.",
    "La musculation vous aide à construire un corps et un esprit plus fort.",
    "L'entraînement est la clé pour développer votre détermination et votre persévérance.",
    "La musculation vous permet de dépasser vos limites et de devenir la meilleure version de vous-même.",
    "L'effort physique est la clé pour développer votre discipline et votre mentalité de gagnant.",
    "La musculation vous aide à construire une vie plus saine et plus forte.",
    "La musculation est la clé pour développer votre force physique et mentale.",
    "L'entraînement quotidien vous aide à atteindre vos objectifs à long terme.",
    "La persévérance est la clé pour construire un corps fort et un esprit plus fort.",
    "La musculation vous aide à développer votre confiance en vous.",
    "L'entraînement est la clé pour développer votre détermination et votre persévérance.",
    "Le succès en musculation vient de la persévérance à surmonter les défis.",
    "La musculation vous aide à construire un corps plus fort et une vie plus saine.",
    "L'effort physique est la clé pour développer votre discipline et votre mentalité de gagnant.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en sport.",
    "La musculation vous aide à découvrir votre véritable potentiel.",
    "L'entraînement est la clé pour construire une mentalité de gagnant.",
    "La musculation vous permet de dépasser vos limites et de devenir la meilleure version de vous-même.",
    "L'effort physique est la clé pour développer votre force intérieure.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en musculation.",
    "Le succès en musculation vient de la détermination à ne jamais abandonner.",
    "La musculation vous aide à construire un corps et un esprit plus fort.",
    "L'entraînement est la clé pour développer votre détermination et votre persévérance.",
    "La musculation vous permet de développer votre confiance en vous.",
    "L'effort physique est la clé pour construire une vie plus saine et plus forte.",
    "La persévérance est la clé pour construire un corps fort et un esprit plus fort.",
    "La musculation vous aide à atteindre vos objectifs à long terme.",
    "L'entraînement quotidien est la clé pour développer votre discipline et votre mentalité de gagnant.",
    "La musculation est la clé pour développer votre force physique et mentale.",
    "L'effort physique est la clé pour développer votre force intérieure.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en sport.",
    "La musculation vous aide à découvrir votre véritable potentiel.",
    "L'entraînement est la clé pour construire une mentalité de gagnant.",
    "La musculation vous permet de dépasser vos limites et de devenir la meilleure version de vous-même.",
    "L'effort physique est la clé pour construire une vie plus saine et plus forte",
    "La persévérance est la clé pour développer votre détermination et votre persévérance.",
    "La musculation vous aide à construire un corps plus fort et une vie plus équilibrée.",
    "L'entraînement quotidien vous aide à développer votre discipline et votre mentalité de gagnant.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en musculation.",
    "La musculation vous permet de développer votre force physique et mentale.",
    "L'entraînement est la clé pour développer votre confiance en vous.",
    "Le succès en musculation vient de la persévérance à travailler dur chaque jour.",
    "La musculation vous aide à construire une vie plus saine et plus forte.",
    "L'effort physique est la clé pour développer votre force intérieure et votre mentalité de gagnant.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en sport.",
    "La musculation vous permet de découvrir votre véritable potentiel et de devenir la meilleure version de vous-même.",
    "L'entraînement quotidien vous aide à construire une mentalité de gagnant et une vie plus équilibrée.",
    "La musculation est la clé pour construire une vie plus saine et plus forte.",
    "L'entraînement quotidien vous aide à développer votre détermination et votre persévérance.",
    "La persévérance est la clé pour atteindre vos objectifs en musculation.",
    "La musculation vous permet de développer votre force physique et mentale.",
    "L'effort physique est la clé pour construire une mentalité de gagnant.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en sport.",
    "La musculation vous aide à découvrir votre véritable potentiel et à devenir plus fort chaque jour.",
    "L'entraînement quotidien vous aide à développer votre confiance en vous.",
    "Le succès en musculation vient de la persévérance à travailler dur chaque jour.",
    "La musculation vous aide à construire un corps plus fort et une mentalité de gagnant.",
    "L'effort physique est la clé pour développer votre force intérieure et votre détermination.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en musculation.",
    "La musculation vous permet de développer votre discipline et votre mentalité de gagnant.",
    "L'entraînement quotidien vous aide à construire une vie plus saine et plus forte.",
    "La musculation est la clé pour développer votre force physique et mentale.",
    "L'effort physique est la clé pour construire une mentalité de gagnant.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en sport.",
    "La musculation vous aide à découvrir votre véritable potentiel et à devenir plus fort chaque jour.",
    "L'entraînement quotidien vous aide à développer votre confiance en vous.",
    "Le succès en musculation vient de la persévérance à travailler dur chaque jour.",
    "La musculation vous aide à construire un corps plus fort et une mentalité de gagnant.",
    "L'effort physique est la clé pour développer votre force intérieure et votre détermination.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en musculation.",
    "La musculation vous permet de développer votre discipline et votre mentalité de gagnant.",
    "L'entraînement quotidien vous aide à construire une vie plus saine et plus forte.",
    "La musculation est la clé pour développer votre force physique et mentale.",
    "L'effort physique est la clé pour construire une mentalité de gagnant.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en sport.",
    "La musculation vous aide à découvrir votre véritable potentiel et à atteindre vos objectifs.",
    "L'entraînement quotidien est la clé pour développer votre discipline et votre mentalité de gagnant.",
    "La persévérance est la clé pour construire une vie plus saine et plus forte.",
    "La musculation vous permet de développer votre force physique et votre confiance en vous.",
    "L'effort physique est la clé pour développer votre force intérieure et votre détermination.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en musculation.",
    "La musculation vous aide à construire un corps plus fort et une mentalité de gagnant.",
    "L'entraînement quotidien est la clé pour construire une vie plus saine et plus équilibrée.",
    "Le succès en musculation vient de la persévérance à travailler dur et à ne jamais abandonner.",
    "La musculation vous permet de découvrir votre véritable potentiel et de devenir la meilleure version de vous-même.",
    "L'entraînement quotidien vous aide à développer votre confiance en vous et votre mentalité de gagnant.",
    "La persévérance est la clé pour construire un corps fort et un esprit plus fort.",
    "La musculation vous aide à développer votre force physique et votre discipline.",
    "L'effort physique est la clé pour construire une mentalité de gagnant et une vie plus équilibrée.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en musculation.",
    "La musculation vous permet de devenir plus fort chaque jour et de découvrir votre véritable potentiel.",
    "L'entraînement quotidien vous aide à construire une mentalité de gagnant et une vie plus saine.",
    "Le succès en musculation vient de la persévérance à travailler dur et à ne jamais abandonner.",
    "La musculation vous aide à construire un corps plus fort et une confiance en vous plus solide.",
    "L'effort physique est la clé pour développer votre force intérieure et votre détermination.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en musculation.",
    "La musculation vous permet de découvrir votre véritable potentiel et de devenir la meilleure version de vous-même.",
    "L'entraînement quotidien vous aide à développer votre discipline et votre mentalité de gagnant.",
    "La persévérance est la clé pour construire une vie plus saine et plus forte.",
    "La musculation vous aide à développer votre force physique et votre confiance en vous.",
    "L'effort physique est la clé pour développer votre détermination et votre persévérance.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en sport.",
    "La musculation vous permet de construire un corps plus fort et une mentalité de gagnant.",
    "L'entraînement quotidien vous aide à développer votre discipline et votre confiance en vous.",
    "Le succès en musculation vient de la persévérance à ne jamais abandonner et à travailler dur.",
    "La musculation vous aide à découvrir votre véritable potentiel et à devenir plus fort chaque jour.",
    "L'entraînement quotidien vous aide à construire une vie plus équilibrée et plus saine.",
    "La persévérance est la clé pour développer votre force intérieure et votre mentalité de gagnant.",
    "La musculation vous permet de développer votre détermination et votre persévérance.",
    "L'effort physique est la clé pour atteindre vos objectifs en musculation et en sport.",
    "La persévérance et la détermination sont la clé pour construire un corps fort et un esprit plus fort.",
    "La musculation vous aide à développer votre confiance en vous et votre mentalité de gagnant.",
    "L'entraînement quotidien vous aide à découvrir votre véritable potentiel et à devenir la meilleure version de vous-même.",
    "Le succès en musculation vient de la persévérance à travailler dur et à ne jamais abandonner.",
    "La musculation vous aide à construire un corps plus fort et une mentalité plus forte.",
    "L'effort physique est la clé pour développer votre force intérieure et votre détermination.",
    "La persévérance et la détermination sont la clé pour atteindre vos objectifs en musculation et en sport.",
    "La musculation vous permet de découvrir votre véritable potentiel et de devenir plus fort chaque jour.",
    "L'entraînement quotidien vous aide à construire une mentalité de gagnant et une vie plus saine.",
    "La musculation est le moyen de découvrir votre force intérieure et votre potentiel.",
    "L'entraînement quotidien vous aide à développer votre détermination et votre persévérance.",
    "La persévérance est la clé pour construire un corps plus fort et une mentalité plus forte.",
    "La musculation vous permet de développer votre force physique et votre confiance en vous.",
    "L'effort physique est la clé pour atteindre vos objectifs en musculation et en sport.",
    "La persévérance et la détermination sont la clé pour découvrir votre véritable potentiel.",
    "La musculation vous aide à construire une mentalité de gagnant et une vie plus équilibrée.",
    "L'entraînement quotidien vous aide à développer votre discipline et votre force mentale.",
    "Le succès en musculation vient de la persévérance à travailler dur et à croire en vous-même.",
    "La musculation vous permet de devenir plus fort chaque jour et de construire une vie plus saine.",
    "L'entraînement quotidien vous aide à développer votre confiance en vous et votre mentalité de gagnant.",
    "La persévérance est la clé pour développer votre force intérieure et votre détermination.",
    "La musculation vous aide à atteindre vos objectifs en musculation et en sport.",
    "L'effort physique est la clé pour construire un corps plus fort et un esprit plus fort.",
    "La persévérance et la détermination sont la clé pour découvrir votre véritable potentiel.",
    "La musculation vous permet de développer votre force physique et votre mentalité de gagnant.",
    "L'entraînement quotidien vous aide à construire une vie plus équilibrée et plus saine.",
    "Le succès en musculation vient de la persévérance à travailler dur et à ne jamais abandonner.",
    "La musculation vous aide à découvrir votre force intérieure et votre potentiel.",
    "L'entraînement quotidien vous aide à développer votre détermination et votre persévérance.",
    "La persévérance est la clé pour construire un corps plus fort et une mentalité plus forte.",
    "La musculation vous permet de développer votre force physique et votre confiance en vous.",
    "L'effort physique est la clé pour atteindre vos objectifs en musculation et en sport.",
    "La persévérance et la détermination sont la clé pour découvrir votre véritable potentiel.",
    "La musculation vous aide à construire une mentalité de gagnant et une vie plus équilibrée.",
    "L'entraînement quotidien vous aide à développer votre discipline et votre force mentale.",
    "Le succès en musculation vient de la persévérance à travailler dur et à croire en vous-même.",
    "La musculation vous permet de devenir plus fort chaque jour et de construire une vie plus saine.",
    "L'entraînement quotidien vous aide à développer votre confiance en vous et votre mentalité de gagnant.",
    "La persévérance est la clé pour développer votre force intérieure et votre détermination.",
    "La musculation vous aide à atteindre vos objectifs en musculation et en sport.",
    "L'effort physique est la clé pour construire un corps plus fort et un esprit plus fort.",
    "La persévérance et la détermination sont la clé pour découvrir votre véritable potentiel.",
    "La musculation vous permet de développer votre force physique et votre mentalité de gagnant.",
    "L'entraînement quotidien vous aide à construire une vie plus équilibrée et plus saine.",
    "Le succès en musculation vient de la persévérance à travailler dur et à ne jamais abandonner.",
    "La musculation vous aide à découvrir votre force intérieure et votre potentiel.",
    "L'entraînement quotidien vous aide à développer votre détermination et votre persévérance.",
    "La persévérance est la clé pour construire un corps plus fort et une mentalité plus forte.",
    "La musculation vous permet de développer votre force physique et votre confiance en vous.",
    "L'effort physique est la clé pour atteindre vos objectifs en musculation et en sport.",
    "La persévérance et la détermination sont la clé pour découvrir votre véritable potentiel.",
    "La musculation vous aide à construire une mentalité de gagnant et une vie plus équilibrée.",
    "L'entraînement quotidien vous aide à développer votre discipline et votre force mentale.",
    "Le succès en musculation vient de la persévérance à travailler dur et à croire en vous-même.",
    "La musculation vous permet de devenir plus fort chaque jour et de construire une vie plus saine.",
    "L'entraînement quotidien vous aide à développer votre confiance en vous et votre mentalité de gagnant.",
    "La musculation est un voyage vers votre propre force et votre meilleure version.",
    "L'entraînement quotidien est un investissement en votre santé et votre bien-être.",
    "La persévérance est le moyen de découvrir votre véritable potentiel et de le réaliser.",
    "La musculation vous permet de développer votre force physique et votre confiance en vous.",
    "L'effort physique est la clé pour découvrir votre détermination et votre persévérance.",
    "La persévérance et la détermination sont le moyen de réaliser vos rêves en musculation.",
    "La musculation vous aide à construire un corps plus fort et une mentalité plus positive.",
    "L'entraînement quotidien vous aide à développer votre discipline et votre force mentale.",
    "Le succès en musculation vient de la persévérance à travailler dur et à croire en vous-même.",
    "La musculation vous permet de vous surpasser chaque jour et de construire une vie plus saine.",
    "L'entraînement quotidien vous aide à développer votre confiance en vous et votre estime de soi.",
    "La persévérance est la clé pour découvrir votre véritable potentiel et de le réaliser.",
    "La musculation vous aide à développer votre force physique et votre détermination.",
    "L'effort physique est la clé pour découvrir votre persévérance et votre force intérieure.",
    "La persévérance et la détermination sont le moyen de construire un corps plus fort et un esprit plus fort.",
    "La musculation vous aide à construire une mentalité de gagnant et une vie plus équilibrée.",
    "L'entraînement quotidien vous aide à développer votre discipline et votre force mentale.",
    "Le succès en musculation vient de la persévérance à travailler dur et à ne jamais abandonner.",
    "La musculation vous permet de découvrir votre véritable potentiel et de devenir plus fort chaque jour.",
    "L'entraînement quotidien vous aide à construire une confiance en vous plus solide et une mentalité de gagnant.",
    "La persévérance est la clé pour découvrir votre force intérieure et votre détermination.",
    "La musculation vous aide à construire un corps plus fort et une mentalité plus positive.",
    "L'entraînement quotidien vous aide à développer votre discipline et votre force mentale.",
    "Le succès en musculation vient de la persévérance à travailler dur et à croire en vous-même.",
    "La musculation vous permet de vous surpasser chaque jour et de construire une vie plus saine.",
    "L'entraînement quotidien vous aide à développer votre confiance en vous et votre estime de soi.",
    "La persévérance est la clé pour réaliser vos rêves en musculation et en sport.",
    "La musculation vous aide à développer votre force physique et votre détermination.",
    "L'effort physique est le moyen de découvrir votre persévérance et votre force intérieure.",
    "La persévérance et la détermination sont la clé pour construire un corps plus fort et un esprit plus fort.",
    "La musculation vous permet de construire une mentalité de gagnant et une vie plus équilibrée.",
    "L'entraînement quotidien vous aide à développer votre discipline et votre force mentale.",
    "Le succès en musculation vient de la persévérance à travailler dur et à ne jamais abandonner.",
    "La musculation vous aide à découvrir votre véritable potentiel et à devenir plus fort chaque jour.",
    "L'entraînement quotidien vous aide à construire une confiance en vous plus solide et une mentalité de gagnant.",
    "La persévérance est la clé pour découvrir votre force intérieure et votre détermination.",
    "La musculation vous aide à construire un corps plus fort et une mentalité plus positive.",
    "L'entraînement quotidien vous aide à développer votre discipline et votre force mentale.",
    "Le succès en musculation vient de la persévérance à travailler dur et à croire en vous-même.",
    "La musculation vous permet de vous surpasser chaque jour et de construire une vie plus saine.",
    "L'entraînement quotidien vous aide à développer votre confiance en vous et votre estime de soi.",
    "La persévérance est la clé pour réaliser vos rêves en musculation et en sport.",
    "La musculation vous aide à développer votre force physique et votre détermination.",
    "L'effort physique est le moyen de découvrir votre persévérance et votre force intérieure.",
    "La persévérance et la détermination sont la clé pour construire un corps plus fort et un esprit plus fort."
  ];


  module.exports = {
    motivationMessages
  };